using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Minor Code Smell", "S1643:Strings should not be concatenated using '+' in a loop", Justification = "<Pending>", Scope = "member", Target = "~M:BulkThumbnailCreator.FFmpegHandler.RunFFMPG(System.Collections.Generic.Dictionary{System.String,System.String},System.String,BulkThumbnailCreator.Settings)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Critical Code Smell", "S2223:Non-constant static fields should not be visible", Justification = "<Pending>", Scope = "member", Target = "~F:BulkThumbnailCreator.Mocking.BTCRunCount")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:BulkThumbnailCreator.Production.VerifyDirectoryAndExeIntegrity(BulkThumbnailCreator.Settings)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1866:Use char overload", Justification = "<Pending>", Scope = "member", Target = "~M:BulkThumbnailCreator.Services.CreatorService.CreatePictureDataVariety(BulkThumbnailCreator.PictureClasses.PictureData,BulkThumbnailCreator.Settings,BulkThumbnailCreator.Job)~System.Threading.Tasks.Task{System.Collections.Generic.List{System.String}}")]
[assembly: SuppressMessage("Major Bug", "S1751:Loops with at most one iteration should be refactored", Justification = "<Pending>", Scope = "member", Target = "~M:BulkThumbnailCreator.Services.CreatorService.SetPictureDataImageDisplayCorrelationForVarietyList(System.String)~BulkThumbnailCreator.PictureClasses.PictureData")]
[assembly: SuppressMessage("Major Code Smell", "S2589:Boolean expressions should not be gratuitous", Justification = "<Pending>", Scope = "member", Target = "~M:BulkThumbnailCreator.Services.CreatorService.SetPictureDataImageDisplayCorrelationForVarietyList(System.String)~BulkThumbnailCreator.PictureClasses.PictureData")]
[assembly: SuppressMessage("Major Code Smell", "S1118:Utility classes should not have public constructors", Justification = "<Pending>", Scope = "type", Target = "~T:BulkThumbnailCreator.Services.UserStateService")]
[assembly: SuppressMessage("Roslynator", "RCS1102:Make class static", Justification = "<Pending>", Scope = "type", Target = "~T:BulkThumbnailCreator.Services.UserStateService")]
